### ISSUE TITLE
helpme，come from china 。I got an error when I clicked "Generate Video" on the page of 127.0.0.1:7860. Has anyone else encountered this situation? http://127.0.0.1:7860/

### ISSUE THREAD

**Issue by ysnick** [CyberAgentAILab/TANGO#11]
I got an error when I clicked "Generate Video" on the page of 127.0.0.1:7860. Has anyone else encountered this situation? http://127.0.0.1:7860/

Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://29f7bf7dc93d819dc0.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
D:\Project\python\tango\TANGO-main\datasets/data_json/youtube_test/speaker1.json
Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/wav2vec2-base-960h/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\models\wav2vec2\processing_wav2vec2.py", line 51, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\processing_utils.py", line 184, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\processing_utils.py", line 228, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\feature_extraction_utils.py", line 338, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\feature_extraction_utils.py", line 438, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 925, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/wav2vec2-base-960h/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))"), '(Request ID: bfce30cf-9dbc-4ed3-8111-a2cb601e242a)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/wav2vec2-base-960h/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\Project\python\tango\TANGO-main\app.py", line 599, in tango
    model = init_class(cfg.model.name_pyfile, cfg.model.class_name, cfg)
  File "D:\Project\python\tango\TANGO-main\app.py", line 452, in init_class
    instance = model_class(config, **kwargs)
  File "D:\Project\python\tango\TANGO-main\models\jointembedding_high_env0.py", line 270, in __init__
    self.audio_processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\models\wav2vec2\processing_wav2vec2.py", line 62, in from_pretrained
    feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\feature_extraction_utils.py", line 338, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\feature_extraction_utils.py", line 438, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 925, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/wav2vec2-base-960h/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))"), '(Request ID: 1b605f5a-c41c-454a-a081-8601f5b97a21)')
D:\Project\python\tango\TANGO-main\datasets/data_json/youtube_test/speaker1.json
Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/wav2vec2-base-960h/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\models\wav2vec2\processing_wav2vec2.py", line 51, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\processing_utils.py", line 184, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\processing_utils.py", line 228, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\feature_extraction_utils.py", line 338, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\feature_extraction_utils.py", line 438, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 925, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/wav2vec2-base-960h/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))"), '(Request ID: 2ccea951-8416-443b-862d-2d18f9be849c)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "C:\Users\Ysnick\.conda\envs\tango\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/wav2vec2-base-960h/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\Project\python\tango\TANGO-main\app.py", line 599, in tango
    model = init_class(cfg.model.name_pyfile, cfg.model.class_name, cfg)
  File "D:\Project\python\tango\TANGO-main\app.py", line 452, in init_class
    instance = model_class(config, **kwargs)
  File "D:\Project\python\tango\TANGO-main\models\jointembedding_high_env0.py", line 270, in __init__
    self.audio_processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\models\wav2vec2\processing_wav2vec2.py", line 62, in from_pretrained
    feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\feature_extraction_utils.py", line 338, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\feature_extraction_utils.py", line 438, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 925, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\Ysnick\.conda\envs\tango\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /facebook/wav2vec2-base-960h/resolve/main/preprocessor_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)')))"), '(Request ID: ff9f7e00-94c6-487c-81bf-412dfb743678)')

**Comment by tsxxdw** [comment]
我本地电脑已经跑通了，云平台的部署也跑通了，你应该是在云平台部署对吧？linux？如果是的，那就应该是代理的问题，云端的服务器大概率是开了代理的，所以导致huggingface下载的时候出现了证书校验的问题。这里我提供2个解决办法，第一个是联系工作人员，他们也许会有办法（不推荐，因为他们也搞不定），第二种是换一个平台，我就是换了一个云平台就搞定了，我用的是矩阵云(https://matgo.cn/),办法已经告诉你了，如果还是不行，可以给我发邮箱，我帮你远程，494456995@qq.com（有偿的，300元）,对了如果是本地电脑部署的化，要修改部分代码才行，不然也报错。

**Comment by abnerLeeqinghao** [comment]
我也是这个一样的问题，请问您解决没有
