### ISSUE TITLE
I have troubles in this when i test my own character

### ISSUE THREAD

**Issue by qiqi0308** [CyberAgentAILab/TANGO#3]
my error code for list

Traceback (most recent call last):
  File "E:\main_project\TANGO-main\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\main_project\TANGO-main\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\main_project\TANGO-main\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "E:\main_project\TANGO-main\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\main_project\TANGO-main\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\main_project\TANGO-main\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "E:\main_project\TANGO-main\env\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "E:\main_project\TANGO-main\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\main_project\TANGO-main\app.py", line 618, in tango
    result = test_fn(model, device, 0, cfg.data.test_meta_paths, test_path, cfg, audio_path, create_graph=create_graph)
  File "E:\main_project\TANGO-main\app.py", line 179, in test_fn
    graph = igraph.Graph.Read_Pickle(fname=pool_path)
  File "E:\main_project\TANGO-main\env\lib\site-packages\igraph\io\files.py", line 223, in _construct_graph_from_pickle_file
    raise IOError(
OSError: Cannot load file. If fname is a file name, that filename may be incorrect.

i wonder how to solve it and why try your example is correct

**Comment by qiqi0308** [comment]
I find i trying your example is incorrect else,becaues output is the same 
![1730347136780](https://github.com/user-attachments/assets/e651fb4e-376c-43b3-9d47-042bd0bc35c6)

**Comment by PigPigchick** [comment]
> I find i trying your example is incorrect else,becaues output is the same ![1730347136780](https://private-user-images.githubusercontent.com/162962703/381819629-e651fb4e-376c-43b3-9d47-042bd0bc35c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjk0MDMsIm5iZiI6MTczMjM2OTEwMywicGF0aCI6Ii8xNjI5NjI3MDMvMzgxODE5NjI5LWU2NTFmYjRlLTM3NmMtNDNiMy05ZDQ3LTA0MmJkMGJjMzVjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxMzM4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmNlNjY2NjYxYjU2YWE4NjhhOWNjMzg1YWVlZGQ1ODMzY2YyNzI2YTczOThkNzgyMmVkNGQyMmQxMTRjMDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kh43r8m3eXBG7Dl8kDxdvPzymCN3uI-MsQVcNHkLQT4)

me too，did you resolve？

**Comment by PigPigchick** [comment]
> I find i trying your example is incorrect else,becaues output is the same ![1730347136780](https://private-user-images.githubusercontent.com/162962703/381819629-e651fb4e-376c-43b3-9d47-042bd0bc35c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjIzMjIsIm5iZiI6MTczMjQyMjAyMiwicGF0aCI6Ii8xNjI5NjI3MDMvMzgxODE5NjI5LWU2NTFmYjRlLTM3NmMtNDNiMy05ZDQ3LTA0MmJkMGJjMzVjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwNDIwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA5ZTY5NTliNGEwOWYxZGY4YmNiM2ZkZTliMzFiNDQwODc5MTk5NTA3NGM4MGFlMGFkNTI2NmY0OTQ5NjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gfnl7WVn_RmloxrIOqmHMUYQaT7uJLGn2aR4GDpjruk)

I think i have resolved,you should change the line 571 ,change speaker1.json to speaker7.json or other.
```python

``` yaml_name = os.path.join(SCRIPT_PATH, "datasets/data_json/youtube_test/speaker1.json")

**Comment by qiqi0308** [comment]
> > I find i trying your example is incorrect else,becaues output is the same ![1730347136780](https://private-user-images.githubusercontent.com/162962703/381819629-e651fb4e-376c-43b3-9d47-042bd0bc35c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjIzMjIsIm5iZiI6MTczMjQyMjAyMiwicGF0aCI6Ii8xNjI5NjI3MDMvMzgxODE5NjI5LWU2NTFmYjRlLTM3NmMtNDNiMy05ZDQ3LTA0MmJkMGJjMzVjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwNDIwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA5ZTY5NTliNGEwOWYxZGY4YmNiM2ZkZTliMzFiNDQwODc5MTk5NTA3NGM4MGFlMGFkNTI2NmY0OTQ5NjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gfnl7WVn_RmloxrIOqmHMUYQaT7uJLGn2aR4GDpjruk)
> 
> I think i have resolved,you should change the line 571 ,change speaker1.json to speaker7.json or other.
> 
> ```python
> ``` yaml_name = os.path.join(SCRIPT_PATH, "datasets/data_json/youtube_test/speaker1.json")
> ```

thankyou

**Comment by msh1376** [comment]
> > I find i trying your example is incorrect else,becaues output is the same ![1730347136780](https://private-user-images.githubusercontent.com/162962703/381819629-e651fb4e-376c-43b3-9d47-042bd0bc35c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjIzMjIsIm5iZiI6MTczMjQyMjAyMiwicGF0aCI6Ii8xNjI5NjI3MDMvMzgxODE5NjI5LWU2NTFmYjRlLTM3NmMtNDNiMy05ZDQ3LTA0MmJkMGJjMzVjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwNDIwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA5ZTY5NTliNGEwOWYxZGY4YmNiM2ZkZTliMzFiNDQwODc5MTk5NTA3NGM4MGFlMGFkNTI2NmY0OTQ5NjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gfnl7WVn_RmloxrIOqmHMUYQaT7uJLGn2aR4GDpjruk)
> 
> I think i have resolved,you should change the line 571 ,change speaker1.json to speaker7.json or other.
> 
> ```python
> ``` yaml_name = os.path.join(SCRIPT_PATH, "datasets/data_json/youtube_test/speaker1.json")
> ```


Thank you! and how to generate my own character? I upload my voice and my video but it dont generate. we should first train our custom voice and video? if yes, how to do that?

**Comment by qiqi0308** [comment]
I did not train

**Comment by qiqi0308** [comment]
> > > I find i trying your example is incorrect else,becaues output is the same ![1730347136780](https://private-user-images.githubusercontent.com/162962703/381819629-e651fb4e-376c-43b3-9d47-042bd0bc35c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjIzMjIsIm5iZiI6MTczMjQyMjAyMiwicGF0aCI6Ii8xNjI5NjI3MDMvMzgxODE5NjI5LWU2NTFmYjRlLTM3NmMtNDNiMy05ZDQ3LTA0MmJkMGJjMzVjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwNDIwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA5ZTY5NTliNGEwOWYxZGY4YmNiM2ZkZTliMzFiNDQwODc5MTk5NTA3NGM4MGFlMGFkNTI2NmY0OTQ5NjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gfnl7WVn_RmloxrIOqmHMUYQaT7uJLGn2aR4GDpjruk)
> > 
> > 
> > I think i have resolved,you should change the line 571 ,change speaker1.json to speaker7.json or other.
> > ```python
> > ``` yaml_name = os.path.join(SCRIPT_PATH, "datasets/data_json/youtube_test/speaker1.json")
> > ```
> 
> Thank you! and how to generate my own character? I upload my voice and my video but it dont generate. we should first train our custom voice and video? if yes, how to do that?

if you are right ,the gradio will generate directly

**Comment by Nikaat** [comment]
> > > > I find i trying your example is incorrect else,becaues output is the same ![1730347136780](https://private-user-images.githubusercontent.com/162962703/381819629-e651fb4e-376c-43b3-9d47-042bd0bc35c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjIzMjIsIm5iZiI6MTczMjQyMjAyMiwicGF0aCI6Ii8xNjI5NjI3MDMvMzgxODE5NjI5LWU2NTFmYjRlLTM3NmMtNDNiMy05ZDQ3LTA0MmJkMGJjMzVjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwNDIwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA5ZTY5NTliNGEwOWYxZGY4YmNiM2ZkZTliMzFiNDQwODc5MTk5NTA3NGM4MGFlMGFkNTI2NmY0OTQ5NjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gfnl7WVn_RmloxrIOqmHMUYQaT7uJLGn2aR4GDpjruk)
> > > 
> > > 
> > > I think i have resolved,you should change the line 571 ,change speaker1.json to speaker7.json or other.
> > > ```python
> > > ``` yaml_name = os.path.join(SCRIPT_PATH, "datasets/data_json/youtube_test/speaker1.json")
> > > ```
> > 
> > 
> > Thank you! and how to generate my own character? I upload my voice and my video but it dont generate. we should first train our custom voice and video? if yes, how to do that?
> 
> if you are right ,the gradio will generate directly

You mean you just upload your custom character video in mp4 format and custom voice and it automatically generate your own character speach? without any train on your custom voice and video?

**Comment by qiqi0308** [comment]
> > > > > I find i trying your example is incorrect else,becaues output is the same ![1730347136780](https://private-user-images.githubusercontent.com/162962703/381819629-e651fb4e-376c-43b3-9d47-042bd0bc35c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjIzMjIsIm5iZiI6MTczMjQyMjAyMiwicGF0aCI6Ii8xNjI5NjI3MDMvMzgxODE5NjI5LWU2NTFmYjRlLTM3NmMtNDNiMy05ZDQ3LTA0MmJkMGJjMzVjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwNDIwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA5ZTY5NTliNGEwOWYxZGY4YmNiM2ZkZTliMzFiNDQwODc5MTk5NTA3NGM4MGFlMGFkNTI2NmY0OTQ5NjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gfnl7WVn_RmloxrIOqmHMUYQaT7uJLGn2aR4GDpjruk)
> > > > 
> > > > 
> > > > I think i have resolved,you should change the line 571 ,change speaker1.json to speaker7.json or other.
> > > > ```python
> > > > ``` yaml_name = os.path.join(SCRIPT_PATH, "datasets/data_json/youtube_test/speaker1.json")
> > > > ```
> > > 
> > > 
> > > Thank you! and how to generate my own character? I upload my voice and my video but it dont generate. we should first train our custom voice and video? if yes, how to do that?
> > 
> > 
> > if you are right ,the gradio will generate directly
> 
> 您的意思是您只需上传 mp4 格式和自定义语音的自定义角色视频，它就会自动生成您自己的角色语音？没有对自定义语音和视频进行任何培训？

“After you upload the video, it will automatically start training without the need for additional training.
