### ISSUE TITLE
ModuleNotFoundError: No module named 'moviepy.editor'

### ISSUE THREAD

**Issue by Zero-Hub** [CyberAgentAILab/TANGO#34]
![Uploading image.png…]()

(tango) PS D:\IdeaWork\TANGO> python app.py
Traceback (most recent call last):
  File "D:\IdeaWork\TANGO\app.py", line 25, in <module>
    from create_graph import path_visualization, graph_pruning, get_motion_reps_tensor, path_visualization_v2
  File "D:\IdeaWork\TANGO\create_graph.py", line 20, in <module>
    from moviepy.editor import VideoClip, AudioFileClip
ModuleNotFoundError: No module named 'moviepy.editor'
(tango) PS D:\IdeaWork\TANGO> python create_graph.py
Traceback (most recent call last):
  File "D:\IdeaWork\TANGO\create_graph.py", line 20, in <module>
    from moviepy.editor import VideoClip, AudioFileClip
ModuleNotFoundError: No module named 'moviepy.editor'
(tango) PS D:\IdeaWork\TANGO>

**Comment by soooocold** [comment]
try  
pip uninstall moviepy
pip install moviepy==1.0.3
